/**
 * Engineering Firebase — DEDICATED project `mango-engineering`.
 * Auto-generated by scripts/eng-pull-config.mjs — do not point at clinical.
 *
 * @type {import('firebase/app').FirebaseOptions | null}
 */
export const engFirebaseOptions = {
  apiKey: "AIzaSyBKb0YdmYSm7DsjRRO4dBxd9V3FyB_-BWc",
  authDomain: "mango-engineering.firebaseapp.com",
  projectId: "mango-engineering",
  storageBucket: "mango-engineering.firebasestorage.app",
  messagingSenderId: "819275254974",
  appId: "1:819275254974:web:1f04341efe36e14ef762ef",
};
